---
title: "Nationscape"
author: "Chad Peltier"
date: "1/12/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Other datasets:
https://www.cdc.gov/nchs/nhis/2019nhis.htm
https://data.humdata.org/


```{r}
library(tidyverse)
library(tidymodels)
library(haven)
library(lubridate)
library(janitor)
library(naniar)

```

# Loading data

file:///C:/Users/ChadPeltier/Downloads/Nationscape_phase2/Nationscape-DataRelease_WeeklyMaterials_DTA/phase_2_v20200814/ns20200625/codebook_ns20200625.pdf



```{r}
path <- "C:\\Users\\ChadPeltier\\Downloads\\Nationscape_phase2\\Nationscape-DataRelease_WeeklyMaterials_DTA\\phase_2_v20200814"

files <- tibble(files = list.files(path))

files <- files %>%
    mutate(files2 = paste0(path, "\\", files))

files2 <- map(files$files2, ~ list.files(.x, full.names = TRUE)) %>%
    enframe() %>%
    unnest(value) %>%
    mutate(value = str_replace(value, "\\/", "\\\\"),
           date = str_extract(value, "(?<=ns)\\d+"),
           date = ymd(date)) %>%
    filter(str_detect(value, "\\.dta$"),
           date > ymd("2020-06-01"))

nationscape <- map_dfr(files2$value, read_dta)

## add citylab cdi data
cdi <- read_csv("https://raw.githubusercontent.com/theatlantic/citylab-data/master/citylab-congress/citylab_cdi.csv") %>%
    clean_names() %>%
    mutate(cd = str_remove(cd, "-"),
           cd = str_replace(cd, "AL", "00"))

## final cleaning, replacing 888s, dropping NAs for ID and weight, changing col types 
nationscape2 <- nationscape %>%
    left_join(cdi %>% select(cd, cluster), by = c("congress_district" = "cd")) %>%
    mutate(across(everything(), as.character),
           across(everything(), ~ str_replace_all(., "888", NA_character_)),
           weight = as.numeric(weight)) %>%
    drop_na(response_id, weight) 

```



# Using the survey package

```{r}
library(survey)

nationscape_svy <- svydesign(id = ~ response_id,
                             data = nationscape2,
                             weights = ~ weight)


## example - means of party identification 
svymean(~pid7, nationscape_svy, na.rm = TRUE) %>%
    as.data.frame() %>% 
    rownames_to_column("group") %>%
    mutate(upper = mean + SE,
           lower = mean - SE,
           group = case_when(group == "pid71" ~ "Strong Democrat",
                             group == "pid72" ~ "Weak Democrat",
                             group == "pid73" ~ "Lean Democrat",
                             group == "pid74" ~ "Independent",
                             group == "pid75" ~ "Lean Republican",
                             group == "pid76" ~ "Weak Republican",
                             group == "pid77" ~ "Strong Republican",
                             TRUE ~ "Other"),
           group = fct_inorder(group)) %>% 
    ggplot(aes(mean, group)) +
    geom_point() +
    geom_errorbar(aes(xmin = lower, xmax = upper), width = 0.2) +
    labs(y = "Party Identification", x = "Percent of US") +
    scale_x_continuous(labels = scales::percent) 

```


# Using the srvyr package


```{r}
library(srvyr)

```

